
name: Qodana

on:
  push:
    branches:
      - "master"

env:
  JAVA_VERSION: 17

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      actions: read
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:
          egress-policy: audit
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: Wandalen/wretry.action@v1.0.36
        timeout-minutes: 5
        with:
          action: actions/setup-java@v3
          with: |
            distribution: temurin
            java-version: ${{ env.JAVA_VERSION }}
          attempt_limit: 3
          attempt_delay: 2000

      - name: Build
        run: ./mvnw package
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2022.2.2