name: "build spring app"

on:
  push:
    branches:
      - "master"

jobs:
  run-tests:
       uses: ./.github/workflows/run-test.yaml

  build-gradle:
    uses: ./.github/workflows/gradle-build.yaml
