name: "build spring app"

on:
  push:
    branches:
      - "master"

jobs:
  run-tests:
       uses: ./.github/workflows/run-test.yaml

  build-gradle:
    uses: ./.github/workflows/gradle-build.yaml

  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.2.2
