name: "build spring app"

on:
  push:
    branches:
      - "master"

jobs:
  run-tests:
       uses: ./.github/workflows/run-test.yaml@master

  build-gradle:
    uses: ./.github/workflows/gradle-build.yaml@master

  push-aws:
    needs:
      - run-tests
      - build-gradle
    uses: ./.github/workflows/push-aws.yaml@master
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}